### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by migounette**
Add Dockerfile in order to produce a Docker image

### CODE REVIEW

**Comment by migounette** [comment]
Humm... moving to python 3.7.3 seems to impact ROPGadget... Digging

**Comment by Boyan-MILANOV** [comment]
Hey ! 
Thanks for contributing, I'll test it and merge as soon as I can :) 
Keep us updated about the python 3.7 issue if you find anything, otherwise I'll check it out. 

Boyan.

**Comment by migounette** [comment]
It's up to date... This is a docker experimental (for this turn), it works on my side, but I was obliged to patch ropgadget in order to get it works with python 3, look at the diff patch.
Maybe it should be intresting to push the change to ropgadget
You did a good job, so I need it :) in my Windows Env.
With a sharing drive you can load and find gadgets.

**Comment by Boyan-MILANOV** [comment]
Tested and approved. I'm merging the PR. 
Thanks for the contribution and have fun pwning with ROPGenerator :D 

Boyan

**Pull request merged**
